name: uy
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cloud_firestore: ^0.14.3+1
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  firebase_storage: "^5.0.1"
  firebase_messaging: ^6.0.13
  firebase_auth_web: ^0.3.2+3
  firebase_core_web: ^0.2.1
  video_player: ^0.10.8+1
  flick_video_player: ^0.1.1
  flutter_staggered_grid_view: ^0.3.4
  shared_preferences: ^0.5.12+4
  animated_text_kit: ^3.1.0
  flutter_spinkit: ^4.1.2+1
  permission_handler: ^5.0.1+1
  google_sign_in: "^4.5.1"
  animated_splash_screen: ^1.0.1+2
  provider: ^4.1.0
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  popup_menu: ^1.0.5
  line_awesome_flutter: ^1.0.1
  path_provider: ^1.6.27
  flutter_typeahead: ^1.8.8
  percent_indicator: ^2.1.9
  flutter_svg: ^0.19.3
  flare_flutter: ^2.0.6
  flutter_offline: "^0.3.0"
  animations: ^1.1.2
  dynamic_text_highlighting: ^2.2.0
  file_picker: ^2.1.7
  ext_storage: ^1.0.3
  
  http: 0.12.2

  flutter_localizations:
    sdk: flutter

  firebase: ^8.0.0
  fluttertoast: ^8.0.7
  universal_html: ^1.2.4
  hovering: ^1.0.4
  shimmer: ^2.0.0
  scrollable_positioned_list: ^0.1.10
  email_auth: ^0.0.1+2
  flutter_staggered_animations: ^1.0.0
  simple_tooltip: ^1.0.0
  countup: ^0.1.3
  psd_sdk: ^0.1.6
  readmore: ^2.1.0
  dropdown_below: ^1.0.0
  mailto: ^1.1.0
  url_launcher: ^5.7.10
  google_maps: ">=3.0.0 <4.0.0"
  geolocator: ^6.2.0
  google_maps_flutter: ^0.5.28
  google_maps_flutter_web: ^0.1.0
  geocoder: ^0.2.0
  location: ^3.2.4
  
 
  
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  
flutter_intl:
    main_locale: en
    enabled: true
    class_name: S
dev_dependencies:
  flutter_test:
    sdk: flutter
module:
  androidX: true
flutter:
  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/feeling/
    - assets/images/journalistKind/
    - assets/icons/
    - assets/icons/file_format/
    
  fonts:
     - family: SPProtext
       fonts:
         - asset: assets/font/FontsFree-Net-SFProDisplay-Thin.ttf
           weight: 100
         - asset: assets/font/FontsFree-Net-SFProText-Regular.ttf
           weight: 400
         - asset: assets/font/FontsFree-Net-SFProText-Medium.ttf
           weight: 500
         - asset: assets/font/FontsFree-Net-SFProText-Bold.ttf
           weight: 600
         
  
     - family: Avenir
       fonts:
         - asset: assets/font/Avenir Book.ttf

     - family: Tajawal
       fonts:
         - asset: assets/font/Tajawal-Light.ttf
         
     - family: DancingScript
       fonts:
         - asset: assets/font/DancingScript-VariableFont_wght.ttf
         

     - family: KaushanScript
       fonts:
         - asset: assets/font/KaushanScript-Regular.ttf
     - family: Roboto
       fonts:
         - asset: assets/font/Roboto-Light.ttf  
         
     - family: MarckScript
       fonts:
         - asset: assets/font/MarckScript-Regular.ttf
     - family: Lora
       fonts:
         - asset: assets/font/Lora-VariableFont_wght.ttf
     - family: "Roberto"
       fonts:
         - asset: assets/font/RobotoSlab-VariableFont_wght.ttf
     - family: "Pacifico"
       fonts:
         - asset: assets/font/Pacifico-Regular.ttf
     - family: "Courgette"
       fonts:
         - asset: assets/font/Courgette-Regular.ttf
 