List<String> businessList = [
  " Economy,"
      "Finance & investment",
  "Company News",
  "Accounting",
  "Advertising & Marketing",
  "Banking & Finance",
  "Business Management",
  "Economics",
  "Entrepreneurship",
  "Franchising",
  "Insurance",
  "Statistics",
];

List<String> lifeStyleList = [
  "Beauty",
  "Cooking, Food & Wine",
  "Diet",
  "Family",
  "Fashion",
  " Gardening",
  "General",
  " Health & Wellbeing",
  " Home",
  " Kids & teens",
  " Parenting & Babies",
  " Sex & Relationship",
  "Adventure & Outdoors",
  "Outdoors Photography",
  "Alternative & Spiritual Lifestyle",
  "Animals & Pets",
  "Beauty & Personal Care",
  "Beer & Brewing",
  "Brides",
  "Caravans",
  "Families & Parenting",
  "Fashion - Men's",
  "Fashion - Women's",
  "Food & Cuisine",
  "Gardening",
  "History & Genealogy",
  "Homes & Interiors",
  "Inflight Magazine",
  "Kids' Stuff",
  "LGBT Lifestyle",
  "Lifestyle",
  "Luxury Lifestyle",
  "Men's Interest",
  "Regional Tourism",
  "Seniors Lifestyle",
  "Student Papers",
  "Travel - Cruises",
  "Women's Interest",
  "Women's Lifestyle Bloggers",
  "Youth Culture",
];

List<String> technologyList = [
  "Hacking",
  "Cyber laws and security",
  "Computer architecture",
  "E-commerce",
  "Web designing",
  "Networking fundamental",
  "Front end technique",
  "Machine learning",
  "Blockchain",
  "Cloud computing",
  "Systems Fundamentals",
  "Software Engineering",
  "Software Development Fundamentals",
  "Programming Languages",
  "Parallel and Distributed Computing",
  "Platform-based Development",
  "Operating Systems",
  "Networking and Communications",
  "Intelligent Systems",
  "Information Management",
  "Information Assurance and Security",
  "Human-Computer Interaction",
  "Graphics and Visualization",
  "Discrete Structures",
  "Computational Science",
  "Architecture and Organization",
  "Algorithms and Complexity",
];

List<String> sportList = [
  "Guns & Hunting",
  "Athletics",
  "Soccer",
  "Basketball",
  "Tennis",
  "Baseball",
  "Golf",
  "Running",
  "Volleyball",
  "Badminton",
  "Swimming",
  "Boxing",
  "Table tennis",
  "Skiing",
  "Ice skating",
  "Roller skating",
  "Cricket",
  "Rugby",
  "Pool",
  "Darts",
  "Bungee jumping",
  "Hang gliding",
  "Sky diving",
  "Kickboxing",
  "Wind surfing",
  "Judo",
  "Scuba diving",
  "Weight lifting",
  "Jet skiing",
  "Water skiing",
  "Fencing",
  "Taekwondo",
  "Sumo wrestling",
  "Rock climbing",
  "Figure skating",
  "Gymnastics",
  "Fishing",
  "Archery",
  "Cycling",
  "Skateboarding",
  "Hnowboarding",
  "Horse racing",
  "Karate",
  "Surfing",
  "Ice hockey",
  "Bowling",
  "Football",
];

List<String> healthList = [
  "Anatomical Pathology",
  "Clinical microbiology",
  "Anesthesiology",
  "Cardiology",
  "Cardiovascular/Thoracic Surgery",
  "Clinical Immunology/Allergy",
  "Critical Care Medicine",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology and Metabolism",
  "Family Medicine",
  "Gastroenterology",
  "General Internal Medicine",
  "General Surgery",
  "General/Clinical Pathology",
  "Geriatric Medicine",
  "Hematology",
  "Immunology",
  "Medical Biochemistry",
  "Medical Genetics",
  "Medical Microbiology and Infectious Diseases",
  "Medical Oncology",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Nuclear Medicine",
  "Obstetrics/Gynecology",
  "Occupational Medicine",
  "Ophthalmology",
  "Orthopedic Surgery",
  "Otolaryngology",
  "Pediatrics",
  "Laboratory medicine",
  "Pharmacology",
  "Physical Medicine and Rehabilitation",
  "Plastic Surgery",
  "Psychiatry",
  "Preventive medicine",
  "Podiatric surgery",
  "Pathology",
  "Radiation Oncology",
  "Respirology",
  "Rheumatology",
  "Urology",
  "Tropical medicine",
  "Thoracic surgery",
  "Vascular surgery",
  "Venereology",
  "Stomatology",
  "Physical Health",
  "Mental Health",
  "Emotional Health",
  "Social Health",
  "Environmental Health",
  "Spiritual Health",
  "Family Health",
  "Sexual Health and Reproductive Health",
  "Occupational Health",
  "Public Health",
  "Fitness",
];

List<String> scienceList = [
  "Physics",
  "Chemistry",
  "Earth Science",
  "Space Science",
  "Zoology",
  "Botany",
  "Molecular Biology",
  "Mathematics",
  "Logic",
  "Statistics",
  "Decisions",
  "Sociology",
  "Science education",
  "Archaeology",
  "Political Science",
  "Civil Engineering",
  "Electrical Engineering",
  "Chemical Engineering",
  "Genetic",
  "Operation Research",
  "Industrial",
  "Dental",
  "Oceanography",
  "Microbiology",
  "Ecology",
];

List<String> entertainmentList = [
  "Water Parks",
  "Video Games",
  "Video",
  "Trade Shows",
  "Theme Parks",
  "Streaming Media",
  "Storytelling",
  "Spectator Sports",
  "Social Media",
  "Radio",
  "Podcasts",
  "Operas",
  "Museums",
  "Media",
  "Magic Shows",
  "Karaoke",
  "Festivals",
  "Fashion Shows",
  "Theatre",
  "Dance",
  "Cultural Events",
  "Comedy Clubs",
  "Circuses",
  "Television",
  "Photography",
  "Performing Arts",
  "Music",
  "Movies",
  "Books & Literature",
  "Art & Culture",
];

List<String> agricultureList = [
  "  Nomadic Herding",
  "Livestock Ranching",
  "Shifting Cultivation",
  "Rudimentary Sedentary Tillage",
  "Intensive Subsistence Farming ",
  "Commercial Plantations",
  "Mediterranean Agriculture",
  "Commercial Grain Farming",
  "Livestock and Grain Farming",
  "Subsistence Crop and Stock Farming",
  "Dairy Farming",
  "Specialized Horticulture",
];

List<String> otherList = [
  "Cars",
  "Architecture",
  "Animals",
  "Agriculture, Farming & Rural",
  "Age Care",
  "  4WD, Outdoor, Camping & Caravanning",
  "Transport",
  "Research & Development",
  "Religion",
  "Regional & Country Service",
  "Real stories",
  "Indigenous",
  "Immigration",
  "Human Resources",
  "Hospitality",
  "Gambling",
  "Foreign affairs & trade",
  "Food & Beverage",
  "Federal",
  "Ethnic",
  "Environment",
  "Disability",
  "Community",
  "Childcare",
  "Banking",
  "Aviation",
  "Truck, Bus, Rail & Heavy Machinery",
  "Travel & Tourism Trade",
  "Training",
  "Timber Trade",
  "Swimming Pools & Spas",
  "Rural & Agriculture",
  "Printing & Publishing",
  "Polymers & Plastics",
  "Occupational Health & Safety",
  "Obituaries & Funerals",
  "Meetings & Trade Shows",
  "Manufacturing",
  "Law",
  "Infrastructure",
  "Human Resources Professionals",
  "Hotels, Clubs & Hospitality",
  "Food, Snack & Beverage Trade",
  "Fashion & Apparel Trade",
  "Exports & Supply Chain",
  "Engineering",
  "Education",
  "Defence",
  "Crime, Police & Courts",
  "Cleaning",
  "Building & Construction",
  "Broadcasting Industry",
  "Beauty, Cosmetics & Hair Trade",
  "Aviation & Aerospace",
  "Automotive Trade",
];

List<String> mechanicList = [
  "Diagnostic ",
  "Drive",
  "Heating and Air-conditioning",
  "Electronic Systems",
  "Automatic Transmission",
  "Engine Performance",
  "Air Conditioning ",
  "Race Car",
  "Auto Body",
  "Boat",
  "Small Engine",
  "Bus and Truck",
  "Aircraft ",
  "Industrial Machinery ",
  "Diesel",
  "Electrical",
  "Radio ",
  "Automotive ",
  "Motorcycle",
  "Transportation Systems",
  "System Dynamics",
  "Control",
  "Mechanical Design",
  "Manufacturing",
  "Energy Systems",
  "Thermodynamics",
  "Heat Transfer",
  "Ground Vehicle Systems",
  "Combustion and the Environment",
  "Engineering Fluid Mechanics",
];

List<String> worldList = [
  "Migration",
  "Peace and Security",
  "Politics",
  "International news",
  "Law and Justice",
  "Weather",
  "Stories",
  "Culture",
  "Wars and Conflicts",
];

List<String> alltopic = worldList +
    businessList +
    lifeStyleList +
    technologyList +
    sportList +
    entertainmentList +
    agricultureList +
    mechanicList +
    otherList;




/*"",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", */




